### ISSUE TITLE
Adding timestamps error

### ISSUE THREAD

**Issue by dperlop** [Vendicated/BetterDiscordPlugins#1]
Eii, I downloaded your plugin but when I try to add the timestamps, nothing happens.
Can you check that?, my discord is Perlop

**Comment by lyratcm** [comment]
Had the same issue, uninstalling and reitnalling fixed it for me tho

**Comment by dperlop** [comment]
> Had the same issue, uninstalling and reitnalling fixed it for me tho

I did but nothing solved :(

**Comment by cloudnsephiroth** [comment]
I'm having the same issue, clicking Insert does nothing. Uninstalled and reinstalled but the issue persists.

**Comment by Vendicated** [comment]
thanks for the report! I just fixed it via https://github.com/Vendicated/BetterDiscordPlugins/commit/43a1bf34e382c60ef3cef3c5e141d4492e97b17b. The update will be available once approved
