### ISSUE TITLE
InsertTimestamps button not showing

### ISSUE THREAD

**Issue by RickGotTaken** [Vendicated/BetterDiscordPlugins#10]
self-explanatory
![image](https://github.com/Vendicated/BetterDiscordPlugins/assets/96528846/342b27e9-9259-47c4-ae02-e87d664ee665)

**Comment by Huderon** [comment]
This should be solved in #9, you can grab it there for now

**Comment by RickGotTaken** [comment]
> This should be solved in #9, you can grab it there for now
It worked, thanks!
