### ISSUE TITLE
InsertTimestamps button problem

### ISSUE THREAD

**Issue by vilchu** [Vendicated/BetterDiscordPlugins#2]
After newest update, the button moved to left side and does not connect with the attachment button, as it did previously with being on right side with emoji button
![image](https://github.com/Vendicated/BetterDiscordPlugins/assets/55512609/8e0810b5-abc7-4315-bcb0-e8b192708dd8)
So I wish, there'd be feature where you can maybe choose which side you want the button to be?

**Comment by Vendicated** [comment]
you can do this with css

**Comment by vilchu** [comment]
how?
can you give an example?
